package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Brand identity: forest green (matches the login screen and company logo),
// a warm amber accent for highlights/quick-actions, and a soft blue accent
// for variety — replaces the generic Material purple defaults.

val md_theme_light_primary = Color(0xFF0F6B4E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCFEEDD)
val md_theme_light_onPrimaryContainer = Color(0xFF04321F)
val md_theme_light_secondary = Color(0xFFB77A25)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFCE3C0)
val md_theme_light_onSecondaryContainer = Color(0xFF3D2600)
val md_theme_light_tertiary = Color(0xFF2E6DA4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD3E7FA)
val md_theme_light_onTertiaryContainer = Color(0xFF0A2A40)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFF6FAF8)
val md_theme_light_onBackground = Color(0xFF11201A)
val md_theme_light_surface = Color(0xFFF6FAF8)
val md_theme_light_onSurface = Color(0xFF11201A)
val md_theme_light_surfaceVariant = Color(0xFFE1EAE5)
val md_theme_light_onSurfaceVariant = Color(0xFF414D47)
val md_theme_light_outline = Color(0xFF71857B)

val md_theme_dark_primary = Color(0xFF3FAE81)
val md_theme_dark_onPrimary = Color(0xFF00341F)
val md_theme_dark_primaryContainer = Color(0xFF1B4B39)
val md_theme_dark_onPrimaryContainer = Color(0xFFBFF3DC)
val md_theme_dark_secondary = Color(0xFFE0A75E)
val md_theme_dark_onSecondary = Color(0xFF3A2600)
val md_theme_dark_secondaryContainer = Color(0xFF4A3413)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDDB0)
val md_theme_dark_tertiary = Color(0xFF8FC3EE)
val md_theme_dark_onTertiary = Color(0xFF00304A)
val md_theme_dark_tertiaryContainer = Color(0xFF1D3E52)
val md_theme_dark_onTertiaryContainer = Color(0xFFD2E8FA)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF0E1512)
val md_theme_dark_onBackground = Color(0xFFE7F0EB)
val md_theme_dark_surface = Color(0xFF152019)
val md_theme_dark_onSurface = Color(0xFFE7F0EB)
val md_theme_dark_surfaceVariant = Color(0xFF243128)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2D0C8)
val md_theme_dark_outline = Color(0xFF4C5A52)
