export type StatementReportType =
  | 'quick-customer'
  | 'agent'
  | 'direct-customer'
  | 'vehicle-driver';

export interface StatementRecord {
  id: number;
  reportType: StatementReportType;
  date: string;
  referenceNo: string;
  transactionType: string;
  description: string;
  debit: number;
  credit: number;
  balance: number;
  status: 'مفتوح' | 'مسدد' | 'جزئي' | 'مؤجل' | 'معلق';
  notes: string;
  originalAmount?: number;
  originalCurrency?: 'USD' | 'SYP' | 'TRY';
  exchangeRateToUsd?: number;
  baseAmountUsd?: number;
  entityName: string;
  branch: string;
  city: string;
  shipmentNo?: string;
  senderName?: string;
  receiverName?: string;
  destination?: string;
  transferType?: string;
  agentShare?: number;
  settlementAmount?: number;
  shipmentCount?: number;
  outstandingAmount?: number;
  paymentReference?: string;
  vehicleCode?: string;
  driverName?: string;
  tripRoute?: string;
  fuelExpense?: number;
  tripExpense?: number;
  tripRevenue?: number;
  collectedAmount?: number;
}

export interface ReportConfig {
  id: StatementReportType;
  label: string;
  entityLabel: string;
  entities: string[];
  showCityFilter: boolean;
  showStatusChips: boolean;
}

export const branches = ['كل الفروع', 'دمشق', 'حلب', 'حمص', 'اللاذقية'];
export const cities = ['كل المدن', 'دمشق', 'حلب', 'حمص', 'حماه', 'اللاذقية', 'طرطوس'];

export const reportConfigs: ReportConfig[] = [
  {
    id: 'quick-customer',
    label: 'كشف حساب زبون سريع',
    entityLabel: 'اسم الزبون',
    entities: ['الكل', 'زبون سريع - كشك السوق', 'زبون سريع - معرض المها', 'زبون سريع - متجر البركة'],
    showCityFilter: true,
    showStatusChips: true,
  },
  {
    id: 'agent',
    label: 'كشف حساب وكيل',
    entityLabel: 'اسم الوكيل',
    entities: ['الكل', 'وكيل حلب', 'وكيل حمص', 'وكيل الساحل', 'وكيل حماه'],
    showCityFilter: true,
    showStatusChips: true,
  },
  {
    id: 'direct-customer',
    label: 'كشف حساب عميل دائم',
    entityLabel: 'اسم العميل',
    entities: ['الكل', 'شركة الأصيل التجارية', 'مؤسسة النجاح', 'شركة البناء الحديث', 'متجر النخبة'],
    showCityFilter: false,
    showStatusChips: true,
  },
  {
    id: 'vehicle-driver',
    label: 'كشف مركبة + سائق',
    entityLabel: 'المركبة / السائق',
    entities: ['الكل', '5677-حلب / أحمد محمد', '3421-دمشق / خالد سعيد', '2210-اللاذقية / محمد علي'],
    showCityFilter: false,
    showStatusChips: false,
  },
];

const quickCustomerData: StatementRecord[] = [
  {
    id: 1,
    reportType: 'quick-customer',
    date: '2026-04-02',
    referenceNo: 'QC-0001',
    transactionType: 'شحنة جديدة',
    description: 'إرسال بضاعة مستعجلة إلى حلب',
    debit: 85000,
    credit: 0,
    balance: 85000,
    status: 'مفتوح',
    notes: 'تسليم من الفرع',
    entityName: 'زبون سريع - كشك السوق',
    branch: 'دمشق',
    city: 'حلب',
    shipmentNo: 'SHP-2026-01021',
    senderName: 'زبون سريع - كشك السوق',
    receiverName: 'أحمد الجاسم',
    destination: 'حلب',
  },
  {
    id: 2,
    reportType: 'quick-customer',
    date: '2026-04-04',
    referenceNo: 'QC-0002',
    transactionType: 'دفعة نقدية',
    description: 'تحصيل جزء من قيمة الشحنة',
    debit: 0,
    credit: 30000,
    balance: 55000,
    status: 'جزئي',
    notes: 'تحصيل عبر الصندوق',
    entityName: 'زبون سريع - كشك السوق',
    branch: 'دمشق',
    city: 'حلب',
    shipmentNo: 'SHP-2026-01021',
    senderName: 'زبون سريع - كشك السوق',
    receiverName: 'أحمد الجاسم',
    destination: 'حلب',
    collectedAmount: 30000,
  },
  {
    id: 3,
    reportType: 'quick-customer',
    date: '2026-04-07',
    referenceNo: 'QC-0003',
    transactionType: 'شحنة جديدة',
    description: 'شحنة أدوات منزلية',
    debit: 42000,
    credit: 0,
    balance: 97000,
    status: 'مؤجل',
    notes: 'زبون موسمي',
    entityName: 'زبون سريع - معرض المها',
    branch: 'دمشق',
    city: 'حمص',
    shipmentNo: 'SHP-2026-01055',
    senderName: 'زبون سريع - معرض المها',
    receiverName: 'محمود نعيم',
    destination: 'حمص',
  },
  {
    id: 4,
    reportType: 'quick-customer',
    date: '2026-04-10',
    referenceNo: 'QC-0004',
    transactionType: 'تسوية',
    description: 'إغلاق رصيد مع خصم',
    debit: 0,
    credit: 50000,
    balance: 47000,
    status: 'جزئي',
    notes: 'خصم ترويجي',
    entityName: 'زبون سريع - معرض المها',
    branch: 'دمشق',
    city: 'حمص',
    shipmentNo: 'SHP-2026-01055',
    senderName: 'زبون سريع - معرض المها',
    receiverName: 'محمود نعيم',
    destination: 'حمص',
    collectedAmount: 50000,
  },
  {
    id: 5,
    reportType: 'quick-customer',
    date: '2026-04-12',
    referenceNo: 'QC-0005',
    transactionType: 'شحنة جديدة',
    description: 'بضاعة منسوجات',
    debit: 65000,
    credit: 0,
    balance: 112000,
    status: 'معلق',
    notes: 'بانتظار تأكيد الهاتف',
    entityName: 'زبون سريع - متجر البركة',
    branch: 'حلب',
    city: 'اللاذقية',
    shipmentNo: 'SHP-2026-01081',
    senderName: 'زبون سريع - متجر البركة',
    receiverName: 'سليم درويش',
    destination: 'اللاذقية',
  },
  {
    id: 6,
    reportType: 'quick-customer',
    date: '2026-04-16',
    referenceNo: 'QC-0006',
    transactionType: 'دفعة تحويل',
    description: 'تحويل بنكي',
    debit: 0,
    credit: 112000,
    balance: 0,
    status: 'مسدد',
    notes: 'إقفال كامل',
    entityName: 'زبون سريع - متجر البركة',
    branch: 'حلب',
    city: 'اللاذقية',
    shipmentNo: 'SHP-2026-01081',
    senderName: 'زبون سريع - متجر البركة',
    receiverName: 'سليم درويش',
    destination: 'اللاذقية',
    collectedAmount: 112000,
  },
];

const agentData: StatementRecord[] = [
  {
    id: 101,
    reportType: 'agent',
    date: '2026-04-03',
    referenceNo: 'AG-0001',
    transactionType: 'تحويل عهدة',
    description: 'تحميل مصاريف تشغيل خط حلب',
    debit: 150000,
    credit: 0,
    balance: 150000,
    status: 'مفتوح',
    notes: 'سلفة تشغيل',
    entityName: 'وكيل حلب',
    branch: 'دمشق',
    city: 'حلب',
    transferType: 'تحويل داخلي',
    agentShare: 0,
    settlementAmount: 0,
  },
  {
    id: 102,
    reportType: 'agent',
    date: '2026-04-06',
    referenceNo: 'AG-0002',
    transactionType: 'عمولة وكيل',
    description: 'عمولة شحنات أسبوعية',
    debit: 28000,
    credit: 0,
    balance: 178000,
    status: 'جزئي',
    notes: 'حسب كشف الأسبوع الأول',
    entityName: 'وكيل حلب',
    branch: 'حلب',
    city: 'حلب',
    transferType: 'عمولة',
    agentShare: 28000,
    settlementAmount: 0,
  },
  {
    id: 103,
    reportType: 'agent',
    date: '2026-04-08',
    referenceNo: 'AG-0003',
    transactionType: 'تسوية وكيل',
    description: 'تسوية جزئية عبر تحويل',
    debit: 0,
    credit: 90000,
    balance: 88000,
    status: 'جزئي',
    notes: 'إشعار بنكي رقم 220',
    entityName: 'وكيل حلب',
    branch: 'حلب',
    city: 'حلب',
    transferType: 'تحويل بنكي',
    agentShare: 0,
    settlementAmount: 90000,
  },
  {
    id: 104,
    reportType: 'agent',
    date: '2026-04-09',
    referenceNo: 'AG-0004',
    transactionType: 'عمولة وكيل',
    description: 'عمولة خط الساحل',
    debit: 19000,
    credit: 0,
    balance: 107000,
    status: 'مفتوح',
    notes: 'دورة شهرية',
    entityName: 'وكيل الساحل',
    branch: 'دمشق',
    city: 'اللاذقية',
    transferType: 'عمولة',
    agentShare: 19000,
    settlementAmount: 0,
  },
  {
    id: 105,
    reportType: 'agent',
    date: '2026-04-14',
    referenceNo: 'AG-0005',
    transactionType: 'تسوية وكيل',
    description: 'تسوية كاملة لدورة أبريل',
    debit: 0,
    credit: 107000,
    balance: 0,
    status: 'مسدد',
    notes: 'تم الإقفال',
    entityName: 'وكيل الساحل',
    branch: 'اللاذقية',
    city: 'اللاذقية',
    transferType: 'تسوية نهائية',
    agentShare: 0,
    settlementAmount: 107000,
  },
  {
    id: 106,
    reportType: 'agent',
    date: '2026-04-17',
    referenceNo: 'AG-0006',
    transactionType: 'تحويل عهدة',
    description: 'تغذية صندوق الوكيل',
    debit: 120000,
    credit: 0,
    balance: 120000,
    status: 'معلق',
    notes: 'بانتظار إشعار استلام',
    entityName: 'وكيل حمص',
    branch: 'دمشق',
    city: 'حمص',
    transferType: 'تحويل داخلي',
    agentShare: 0,
    settlementAmount: 0,
  },
];

const directCustomerData: StatementRecord[] = [
  {
    id: 201,
    reportType: 'direct-customer',
    date: '2026-04-01',
    referenceNo: 'DC-0001',
    transactionType: 'فاتورة شحن',
    description: 'شحن دفعة مواد بناء',
    debit: 210000,
    credit: 0,
    balance: 210000,
    status: 'مفتوح',
    notes: 'استحقاق 30 يوم',
    entityName: 'شركة البناء الحديث',
    branch: 'دمشق',
    city: 'حلب',
    shipmentCount: 4,
    outstandingAmount: 210000,
    paymentReference: '-',
  },
  {
    id: 202,
    reportType: 'direct-customer',
    date: '2026-04-05',
    referenceNo: 'DC-0002',
    transactionType: 'دفعة عميل',
    description: 'دفعة أولى من العميل',
    debit: 0,
    credit: 100000,
    balance: 110000,
    status: 'جزئي',
    notes: 'سند قبض RV-2026-00012',
    entityName: 'شركة البناء الحديث',
    branch: 'دمشق',
    city: 'حلب',
    shipmentCount: 0,
    outstandingAmount: 110000,
    paymentReference: 'RV-2026-00012',
  },
  {
    id: 203,
    reportType: 'direct-customer',
    date: '2026-04-09',
    referenceNo: 'DC-0003',
    transactionType: 'فاتورة شحن',
    description: 'شحنة أجهزة',
    debit: 95000,
    credit: 0,
    balance: 205000,
    status: 'مؤجل',
    notes: 'حسب عقد توريد',
    entityName: 'شركة الأصيل التجارية',
    branch: 'حلب',
    city: 'دمشق',
    shipmentCount: 2,
    outstandingAmount: 205000,
    paymentReference: '-',
  },
  {
    id: 204,
    reportType: 'direct-customer',
    date: '2026-04-11',
    referenceNo: 'DC-0004',
    transactionType: 'دفعة تحويل',
    description: 'تحويل بنكي جزئي',
    debit: 0,
    credit: 70000,
    balance: 135000,
    status: 'جزئي',
    notes: 'حوالة بنكية',
    entityName: 'شركة الأصيل التجارية',
    branch: 'حلب',
    city: 'دمشق',
    shipmentCount: 0,
    outstandingAmount: 135000,
    paymentReference: 'BNK-5501',
  },
  {
    id: 205,
    reportType: 'direct-customer',
    date: '2026-04-15',
    referenceNo: 'DC-0005',
    transactionType: 'فاتورة شحن',
    description: 'شحنة موسمية',
    debit: 63000,
    credit: 0,
    balance: 198000,
    status: 'معلق',
    notes: 'بانتظار المطابقة',
    entityName: 'مؤسسة النجاح',
    branch: 'حمص',
    city: 'اللاذقية',
    shipmentCount: 1,
    outstandingAmount: 198000,
    paymentReference: '-',
  },
  {
    id: 206,
    reportType: 'direct-customer',
    date: '2026-04-18',
    referenceNo: 'DC-0006',
    transactionType: 'تسوية نهائية',
    description: 'سداد كامل',
    debit: 0,
    credit: 198000,
    balance: 0,
    status: 'مسدد',
    notes: 'إغلاق الحساب',
    entityName: 'مؤسسة النجاح',
    branch: 'حمص',
    city: 'اللاذقية',
    shipmentCount: 0,
    outstandingAmount: 0,
    paymentReference: 'RV-2026-00021',
  },
];

const vehicleDriverData: StatementRecord[] = [
  {
    id: 301,
    reportType: 'vehicle-driver',
    date: '2026-04-02',
    referenceNo: 'VD-0001',
    transactionType: 'رحلة تشغيل',
    description: 'رحلة دمشق - حلب',
    debit: 0,
    credit: 0,
    balance: 0,
    status: 'مسدد',
    notes: 'حمولة كاملة',
    entityName: '5677-حلب / أحمد محمد',
    branch: 'دمشق',
    city: 'حلب',
    vehicleCode: '5677-حلب',
    driverName: 'أحمد محمد',
    tripRoute: 'دمشق - حلب',
    fuelExpense: 18000,
    tripExpense: 9000,
    tripRevenue: 145000,
    collectedAmount: 120000,
  },
  {
    id: 302,
    reportType: 'vehicle-driver',
    date: '2026-04-05',
    referenceNo: 'VD-0002',
    transactionType: 'رحلة تشغيل',
    description: 'رحلة حلب - دمشق',
    debit: 0,
    credit: 0,
    balance: 0,
    status: 'جزئي',
    notes: 'تحصيل جزئي',
    entityName: '5677-حلب / أحمد محمد',
    branch: 'حلب',
    city: 'دمشق',
    vehicleCode: '5677-حلب',
    driverName: 'أحمد محمد',
    tripRoute: 'حلب - دمشق',
    fuelExpense: 16000,
    tripExpense: 7000,
    tripRevenue: 122000,
    collectedAmount: 70000,
  },
  {
    id: 303,
    reportType: 'vehicle-driver',
    date: '2026-04-08',
    referenceNo: 'VD-0003',
    transactionType: 'رحلة تشغيل',
    description: 'رحلة دمشق - حمص',
    debit: 0,
    credit: 0,
    balance: 0,
    status: 'مفتوح',
    notes: 'بانتظار تحصيل',
    entityName: '3421-دمشق / خالد سعيد',
    branch: 'دمشق',
    city: 'حمص',
    vehicleCode: '3421-دمشق',
    driverName: 'خالد سعيد',
    tripRoute: 'دمشق - حمص',
    fuelExpense: 9000,
    tripExpense: 4500,
    tripRevenue: 76000,
    collectedAmount: 0,
  },
  {
    id: 304,
    reportType: 'vehicle-driver',
    date: '2026-04-10',
    referenceNo: 'VD-0004',
    transactionType: 'رحلة تشغيل',
    description: 'رحلة حمص - دمشق',
    debit: 0,
    credit: 0,
    balance: 0,
    status: 'مسدد',
    notes: 'تم التحصيل',
    entityName: '3421-دمشق / خالد سعيد',
    branch: 'حمص',
    city: 'دمشق',
    vehicleCode: '3421-دمشق',
    driverName: 'خالد سعيد',
    tripRoute: 'حمص - دمشق',
    fuelExpense: 8500,
    tripExpense: 5000,
    tripRevenue: 82000,
    collectedAmount: 82000,
  },
  {
    id: 305,
    reportType: 'vehicle-driver',
    date: '2026-04-14',
    referenceNo: 'VD-0005',
    transactionType: 'رحلة تشغيل',
    description: 'رحلة اللاذقية - دمشق',
    debit: 0,
    credit: 0,
    balance: 0,
    status: 'معلق',
    notes: 'تأخير بالتسوية',
    entityName: '2210-اللاذقية / محمد علي',
    branch: 'اللاذقية',
    city: 'دمشق',
    vehicleCode: '2210-اللاذقية',
    driverName: 'محمد علي',
    tripRoute: 'اللاذقية - دمشق',
    fuelExpense: 13000,
    tripExpense: 7800,
    tripRevenue: 101000,
    collectedAmount: 25000,
  },
  {
    id: 306,
    reportType: 'vehicle-driver',
    date: '2026-04-17',
    referenceNo: 'VD-0006',
    transactionType: 'رحلة تشغيل',
    description: 'رحلة دمشق - اللاذقية',
    debit: 0,
    credit: 0,
    balance: 0,
    status: 'مسدد',
    notes: 'دورة مكتملة',
    entityName: '2210-اللاذقية / محمد علي',
    branch: 'دمشق',
    city: 'اللاذقية',
    vehicleCode: '2210-اللاذقية',
    driverName: 'محمد علي',
    tripRoute: 'دمشق - اللاذقية',
    fuelExpense: 12000,
    tripExpense: 7000,
    tripRevenue: 108000,
    collectedAmount: 108000,
  },
];

export const statementRecords: StatementRecord[] = [
  ...quickCustomerData,
  ...agentData,
  ...directCustomerData,
  ...vehicleDriverData,
].map((record) => {
  const originalAmount =
    record.debit > 0
      ? record.debit
      : record.credit > 0
      ? record.credit
      : record.tripRevenue || 0;

  const currency: 'USD' | 'SYP' | 'TRY' =
    record.id % 3 === 0 ? 'TRY' : record.id % 2 === 0 ? 'SYP' : 'USD';

  const exchangeRateToUsd = currency === 'USD' ? 1 : currency === 'SYP' ? 0.000077 : 0.031;
  const baseAmountUsd = originalAmount * exchangeRateToUsd;

  return {
    ...record,
    originalAmount,
    originalCurrency: currency,
    exchangeRateToUsd,
    baseAmountUsd,
  };
});
