import type { AddressInfo } from 'node:net';
import { app } from '../app.js';
import { pool, testDatabaseConnection } from '../db/pool.js';

type ApiResponse<T> = { success: boolean; data?: T; error?: string };

async function request<T>(
  baseUrl: string,
  path: string,
  init?: RequestInit & { auth?: { userId?: string } },
): Promise<{ status: number; body: ApiResponse<T> }> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (init?.auth?.userId) headers['x-user-id'] = init.auth.userId;

  const response = await fetch(`${baseUrl}${path}`, {
    ...init,
    headers: {
      ...headers,
      ...(init?.headers || {}),
    },
  });
  const body = (await response.json()) as ApiResponse<T>;
  return { status: response.status, body };
}

function ensure(condition: boolean, message: string): void {
  if (!condition) throw new Error(message);
}

async function runFinanceSmoke() {
  await testDatabaseConnection();
  const server = app.listen(0);
  const baseUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;

  try {
    const admin = await pool.query<{ id: string; branch_id: string | null }>(
      `select id, branch_id from users where username = 'admin' limit 1`,
    );
    ensure(Boolean(admin.rowCount), 'Admin user is missing');
    const adminUserId = admin.rows[0].id;
    const branchId = admin.rows[0].branch_id;
    ensure(Boolean(branchId), 'Admin branch scope missing');

    const srs = await request<Array<{ id: string }>>(baseUrl, '/api/v1/senders-receivers');
    ensure(srs.status === 200 && srs.body.success, 'Cannot load sender/receiver');
    const senderId = srs.body.data?.[0]?.id;
    const receiverId = srs.body.data?.[1]?.id || srs.body.data?.[0]?.id;
    ensure(Boolean(senderId && receiverId), 'Missing sender/receiver in seed');

    const shipmentCreate = await request<{ id: string }>(baseUrl, '/api/v1/shipments', {
      method: 'POST',
      auth: { userId: adminUserId },
      body: JSON.stringify({
        shipmentNo: `SHP-FIN-${Date.now()}`,
        senderId,
        receiverId,
        branchId,
        destinationCity: 'Finance City',
        piecesCount: 1,
        status: 'created',
        originalAmount: 110,
        originalCurrency: 'USD',
        exchangeRateToUsd: 1,
        createdBy: adminUserId,
      }),
    });
    ensure(shipmentCreate.status === 201 && shipmentCreate.body.success, 'Shipment creation failed for finance smoke');
    const shipmentId = shipmentCreate.body.data?.id;
    ensure(Boolean(shipmentId), 'Shipment id missing');

    const deliveryCreate = await request<{ id: string }>(baseUrl, '/api/v1/deliveries', {
      method: 'POST',
      auth: { userId: adminUserId },
      body: JSON.stringify({
        deliveryNo: `DEL-FIN-${Date.now()}`,
        shipmentId,
        branchId,
        status: 'delivered',
        recipientName: 'Finance Recipient',
        originalAmount: 110,
        originalCurrency: 'USD',
        exchangeRateToUsd: 1,
        operatorUserId: adminUserId,
      }),
    });
    ensure(deliveryCreate.status === 201 && deliveryCreate.body.success, 'Delivery creation failed');
    const deliveryId = deliveryCreate.body.data?.id;
    ensure(Boolean(deliveryId), 'Delivery id missing');

    const autoGeneratedLookup = await request<Array<{ id: string; delivery_id: string }>>(
      baseUrl,
      `/api/v1/receipt-vouchers?deliveryId=${deliveryId}`,
      { auth: { userId: adminUserId } },
    );
    ensure(autoGeneratedLookup.status === 200 && autoGeneratedLookup.body.success, 'Cannot query auto-generated receipt voucher');
    ensure((autoGeneratedLookup.body.data?.length || 0) >= 1, 'Auto-generated receipt voucher was not created from delivery');

    const duplicateAutoGenerate = await request(baseUrl, `/api/v1/receipt-vouchers/auto-generate-from-delivery/${deliveryId}`, {
      method: 'POST',
      auth: { userId: adminUserId },
    });
    ensure(duplicateAutoGenerate.status === 409, 'Duplicate delivery auto-generation should be rejected');

    const manualReceipt = await request<{ id: string }>(baseUrl, '/api/v1/receipt-vouchers', {
      method: 'POST',
      auth: { userId: adminUserId },
      body: JSON.stringify({
        voucherNo: `RV-MAN-${Date.now()}`,
        branchId,
        shipmentId,
        senderReceiverId: receiverId,
        status: 'confirmed',
        notes: 'Manual receipt smoke',
        originalAmount: 50,
        originalCurrency: 'USD',
        exchangeRateToUsd: 1,
        createdByUserId: adminUserId,
      }),
    });
    ensure(manualReceipt.status === 201 && manualReceipt.body.success, 'Manual receipt voucher creation failed');
    const manualReceiptId = manualReceipt.body.data?.id;

    const manualPayment = await request<{ id: string }>(baseUrl, '/api/v1/payment-vouchers', {
      method: 'POST',
      auth: { userId: adminUserId },
      body: JSON.stringify({
        voucherNo: `PV-MAN-${Date.now()}`,
        branchId,
        shipmentId,
        senderReceiverId: senderId,
        status: 'confirmed',
        notes: 'Manual payment smoke',
        originalAmount: 25,
        originalCurrency: 'USD',
        exchangeRateToUsd: 1,
        createdByUserId: adminUserId,
      }),
    });
    ensure(manualPayment.status === 201 && manualPayment.body.success, 'Manual payment voucher creation failed');
    const manualPaymentId = manualPayment.body.data?.id;

    const cashboxRows = await request<Array<{ source_voucher_type: string; source_voucher_id: string }>>(
      baseUrl,
      '/api/v1/cashbox-transactions',
      { auth: { userId: adminUserId } },
    );
    ensure(cashboxRows.status === 200 && cashboxRows.body.success, 'Cashbox transactions endpoint failed');
    ensure(
      cashboxRows.body.data?.some((row) => row.source_voucher_type === 'receipt' && row.source_voucher_id === manualReceiptId) === true,
      'Cashbox transaction missing for manual receipt voucher',
    );
    ensure(
      cashboxRows.body.data?.some((row) => row.source_voucher_type === 'payment' && row.source_voucher_id === manualPaymentId) === true,
      'Cashbox transaction missing for manual payment voucher',
    );

    const movements = await request<Array<{ voucher_type: string; voucher_id: string }>>(
      baseUrl,
      '/api/v1/party-financial-movements',
      { auth: { userId: adminUserId } },
    );
    ensure(movements.status === 200 && movements.body.success, 'Party movements endpoint failed');
    ensure(
      movements.body.data?.some((row) => row.voucher_type === 'receipt' && row.voucher_id === manualReceiptId) === true,
      'Party movement missing for manual receipt voucher',
    );
    ensure(
      movements.body.data?.some((row) => row.voucher_type === 'payment' && row.voucher_id === manualPaymentId) === true,
      'Party movement missing for manual payment voucher',
    );

    console.info('[PHASE3.1 FINANCE SMOKE] All checks passed.');
  } finally {
    await new Promise<void>((resolve) => server.close(() => resolve()));
    await pool.end();
  }
}

runFinanceSmoke().catch((error) => {
  console.error('[PHASE3.1 FINANCE SMOKE] Failed:', error);
  process.exit(1);
});
